# Site settings
title: 不忘初心
email: mytliulei@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  不忘初心，方得始终
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mytliulei.github.io" # the base hostname & protocol for your site
# twitter_username: mytliulei
github_username:  mytliulei

# Build settings
markdown: kramdown
